name = "apc-optimizer"
version = "0.1.0"
defaultTargets = ["ApcOptimizer", "apc-optimizer"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "ApcOptimizer"

[[lean_exe]]
name = "apc-optimizer"
root = "Main"
