name = "leanr"
version = "0.1.0"
defaultTargets = ["leanr"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "Leanr"

[[lean_exe]]
name = "leanr"
root = "Main"
